source ~/.vim/terminalkeys.vim

call plug#begin()
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'chriskempson/vim-tomorrow-theme'
"Plug 'airblade/vim-gitgutter'
Plug 'mhinz/vim-signify'
Plug 'pangloss/vim-javascript'
Plug 'hail2u/vim-css3-syntax'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'terryma/vim-multiple-cursors'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'vim-airline/vim-airline-themes'
Plug 'pangloss/vim-javascript'
"Plug 'ryym/vim-riot'
Plug 'othree/html5.vim'
Plug 'tpope/vim-fugitive'
call plug#end()

set t_ut=
set number
"autocmd vimenter * NERDTree
colorscheme Tomorrow-Night-Bright
set laststatus=2
set hidden

" Airline 
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_theme = 'luna'


" tmux-navigator
let g:tmux_navigator_no_mappings = 1
"set term=xterm256

nnoremap <silent> <M-Left>  :TmuxNavigateLeft<cr>
"nnoremap <silent> <M-h>  :TmuxNavigateLeft<cr>
nnoremap <silent> <M-Down> :TmuxNavigateDown<cr>
nnoremap <silent> <M-Up> :TmuxNavigateUp<cr>
nnoremap <silent> <M-Right> :TmuxNavigateRight<cr>
"nnoremap <silent> <M-l> :TmuxNavigateRight<cr>
nnoremap <silent> <M-\> :TmuxNavigatePrevious<cr>
nnoremap <silent> `` :b#<cr>
nnoremap <silent> `= :bnext<cr>
nnoremap <silent> `- :bprev<cr>
let c = 1
while c <= 9
	  execute "nnoremap `" . c . " :" . c . "b\<CR>"
	    let c += 1
endwhile

"set <C-Up>=^[OA
"set <C-Down>=^[OB
"set <C-Left>=^[OD
"set <C-Right>=^[OC
map  <plug>NERDTreeTabsToggle<cr>
