#!/bin/bash
ROWS=$(tput lines)
COLS=$(tput cols)

if [ -n "$VID_CONSOLE_LINES" ]; then 
    VIMSIZE=$(expr $ROWS - ${VID_CONSOLE_LINES:-8})
else 
    VIMSIZE=$(echo $ROWS | awk '{ printf("%d", $1 * 0.8) }' )
fi

if [ -n "$TMUX" ]; then
    tmux split-window -v -b -l $VIMSIZE "vim $prefilename $@"
else 
    terminate_after_close="yes"
    tmux new-session -d -x $COLS -y $ROWS $SHELL
    sleep 0.4
    tmux split-window -v -b -l $VIMSIZE "vim $prefilename $@"
fi
tmux select-pane -t 0

if [ "$terminate_after_close" == "yes" ]; then
    tmux -2 attach-session -d
fi
